platform :ios, '6.0'

#pod 'ObjectiveDDP', :git => 'https://github.com/boundsj/ObjectiveDDP.git'
pod 'ObjectiveDDP', :git => '/Users/boundsj/workspace/ios/ObjectiveDDP'
pod 'SocketRocket', :git => 'git@github.com:square/SocketRocket.git'
